# **Lab3: Data Quality & Preprocessing**

**Course**: **INF-604: Data Analysis I** <br>
**Lecturer**: **Sothea HAS, PhD**

-----

**Objective:** In this lab, you will delve deeper into assessing the quality of datasets and employing preprocessing techniques to properly clean them.

------

* Name:
* ID:


------

# 1. [Kaggle Heart Failure Dataset](https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction)

Let's consider **Heart Disease Dataset** dataset discussed in the previous [Lab2](https://hassothea.github.io/Data_Analysis_AUPP/Labs/Lab2_Univariate_Analysis.html).

In [1]:
#| echo: true
#| code-fold: true

import kagglehub
import pandas as pd

# Download latest version
path = kagglehub.dataset_download("fedesoriano/heart-failure-prediction")
data = pd.read_csv(path + "/heart.csv")
data.head()

Using Colab cache for faster access to the 'heart-failure-prediction' dataset.

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

**A.** Using quick statistical summary of each columns, identify the following problems:

- Encode each column into its suitable data type.
- Detect missing values using `data.isna().sum()`. What do you observe?
- Identify columns with invalid values. Count how many invalid data are there in each column?

--------------

In [ ]:
# A.1 Data Type
data.dtypes

Age                 int64
Sex                object
ChestPainType      object
RestingBP           int64
Cholesterol         int64
FastingBS           int64
RestingECG         object
MaxHR               int64
ExerciseAngina     object
Oldpeak           float64
ST_Slope           object
HeartDisease        int64
dtype: object

In [ ]:
data['FastingBS'] = data['FastingBS'].astype(object)
data['HeartDisease'] = data['HeartDisease'].astype(object)
data.dtypes.to_frame().T

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,int64,object,object,int64,int64,object,object,int64,object,float64,object,object

In [ ]:
# Check missing values using .isna().sum()

data.isna().sum().to_frame().T  # there is no missing values that are encoded as Nan.

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Invalid values
data.describe()   # THis is to get all the statistical summaries of the numerical columns.

              Age   RestingBP  Cholesterol       MaxHR     Oldpeak
count  918.000000  918.000000   918.000000  918.000000  918.000000
mean    53.510893  132.396514   198.799564  136.809368    0.887364
std      9.432617   18.514154   109.384145   25.460334    1.066570
min     28.000000    0.000000     0.000000   60.000000   -2.600000
25%     47.000000  120.000000   173.250000  120.000000    0.000000
50%     54.000000  130.000000   223.000000  138.000000    0.600000
75%     60.000000  140.000000   267.000000  156.000000    1.500000
max     77.000000  200.000000   603.000000  202.000000    6.200000

- According to the summary, there are some invalid values within column: 'RestingBP', 'Cholesterol' and 'Oldpeak'.

In [ ]:
# Count
sum(data['RestingBP'] == 0) # There is only 1 person with 0 RestingBP.

1

In [ ]:
data.query("Cholesterol == 0").shape[0]

172

**B. From now, convert invalid data using `NA` encoding.**

- Study its nature: **MCAR, MAR** or **MNAR**? [`Hint`: You should compuare the clean columns before and after dropping the currupted values.]
- Handle them according to your analysis.
- *Outliers*: How many columns contain outliers? List them in a list called `outlier_list = [...]`.

**C. General Information:**

- Visualize if cholesterol is correlated with age or not.
- Visualize if there is any chest pain type that strongly links to heart disease status or not.
- Visualize if diabetes is correlated with heart disease status or not.

## **2. Kaggle [AutoMPG dataset](https://www.kaggle.com/datasets/uciml/autompg-dataset){target="_blank"}**

- Your job is to address if there is any columns containing missing values, invalid values or outliers or not?
- How would you handle the missing values if there is any?

In [ ]:
import kagglehub
import pandas as pd
# Download latest version
path = kagglehub.dataset_download("uciml/autompg-dataset")
auto = pd.read_csv(path + '/auto-mpg.csv')
auto.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

# **Further Reading**

- `Pandas` python library: [https://pandas.pydata.org/docs/getting_started/index.html#getting-started](https://pandas.pydata.org/docs/getting_started/index.html#getting-started)

- `Pandas Cheatsheet`: [https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

- `10 Minute to Pandas`: [https://pandas.pydata.org/docs/user_guide/10min.html](https://pandas.pydata.org/docs/user_guide/10min.html)

- `Some Pandas Lession`: [https://www.kaggle.com/learn/pandas](https://pandas.pydata.org/docs/user_guide/10min.html)